modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"

[[mods]]
modId="haruhicore"
version="${file.jarVersion}"
displayName="Haruhi Core"
credits="Haruhifanclub"
authors="WakelssSloth56"
description='''
'''

[[dependencies.haruhicore]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haruhicore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haruhicore]]
    modId="arnicalib"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="NONE"
    side="BOTH"
