modLoader="javafml"
loaderVersion="[36.2,)"
license="GNU GPLv3"

[[mods]]
modId="haruhicore"
version="${haruhicore_version}"
displayName="Haruhi Core"
credits="Haruhifanclub"
authors="WakelssSloth56"
description='''
'''

[[mods]]
modId="addrlimiter"
version="${addrlimiter_version}"
displayName="Address Limiter"
credits="AUIOC"
authors="WakelssSloth56"
description='''
'''

[[mods]]
modId="ahutils"
version="${ahutils_version}"
displayName="AHUtils"
credits="AUIOC"
authors="WakelssSloth56"
description='''
'''

[[dependencies.haruhicore]]
    modId="forge"
    mandatory=true
    versionRange="[36.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haruhicore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.addrlimiter]]
    modId="forge"
    mandatory=true
    versionRange="[36.2,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.addrlimiter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="SERVER"

[[dependencies.ahutils]]
    modId="forge"
    mandatory=true
    versionRange="[36.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ahutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
