modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"

[[mods]]
modId="haruhiism"
version="${file.jarVersion}"
displayName="Haruhiism"
credits="Haruhifanclub"
authors="WakelssSloth56"
description='''
'''

[[dependencies.haruhiism]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haruhiism]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haruhiism]]
    modId="arnicalib"
    mandatory=true
    versionRange="[5.3.5,)"
    ordering="NONE"
    side="BOTH"
