modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"

[[mods]]
modId="haruhiism"
version="${file.jarVersion}"
displayName="Haruhiism"
credits="HaruhiFanClub, AUIOC"
authors="WakelssSloth56, Libellule505"
description='''
'''

[[dependencies.haruhiism]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haruhiism]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haruhiism]]
    modId="arnicalib"
    mandatory=true
    versionRange="[5.6.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haruhiism]]
    modId="hulsealib"
    mandatory=true
    versionRange="[1.0.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haruhiism]]
    modId="curios"
    mandatory=true
    versionRange="[1.18.2-5.0.0.0,)"
    ordering="NONE"
    side="BOTH"
