modLoader="javafml"
loaderVersion="[39,)"
license="GNU GPLv3"

[[mods]]
modId="haruhicore"
version="${file.jarVersion}"
displayName="Haruhi Core"
credits="Haruhifanclub"
authors="WakelssSloth56"
description='''
'''

[[dependencies.haruhicore]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haruhicore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haruhicore]]
    modId="arnicalib"
    mandatory=true
    versionRange="[4.1.4,)"
    ordering="NONE"
    side="BOTH"
