# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: auto-release

on:
    push:
        tags:
            - 'v*'

jobs:
    first:
        name: Check release tag
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - run: |
                  prop() { grep -P "^\s*[^#]?${1}=.*$" './gradle.properties' | cut -d'=' -f2; }
                  echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
                  echo "HARUHIISM_VERSION=`echo $(prop "haruhiism_version")`" >> $GITHUB_ENV

            - run: if [ "${{env.GIT_TAG}}" != "v${{env.HARUHIISM_VERSION}}" ];then exit 1;fi

    second:
        name: Build and publish
        runs-on: ubuntu-latest
        needs: first
        permissions:
            contents: write
            packages: write

        steps:
            - uses: actions/checkout@v2

            - name: Set up Gradle and clean
              run: |
                  chmod +x ./gradlew
                  rm -rf tmp
                  mkdir tmp

            - name: Build and publish package with Gradle
              env:
                  IS_RELEASE: true
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  ORG_GRADLE_PROJECT_signingKey: ${{secrets.RELEASE_SIGNING_GPG_PRIVATE_KEY}}
                  ORG_GRADLE_PROJECT_signingPassword: ${{secrets.RELEASE_SIGNING_GPG_PASSPHRASE}}
              run: ./gradlew clean build publish genUpdateJson outputProjectFullName

            # - name: Update update JSON
            #   uses: JamesIves/github-pages-deploy-action@4.1.5
            #   with:
            #       clean: false
            #       target-folder: update
            #       branch: gh-pages
            #       folder: tmp

            - name: Github release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: ${{secrets.GITHUB_TOKEN}}
                  prerelease: false
                  files: |
                      build/libs/*.jar
                      build/libs/*.asc
