name: build-test

on: workflow_dispatch

jobs:
    first:
        name: Check and set variables
        runs-on: ubuntu-latest
        outputs:
            ci_version: ${{ steps.set_outputs.outputs.ci_version }}
            full_version: ${{ steps.set_outputs.outputs.full_version }}

        steps:
            - uses: actions/checkout@v2

            - id: set_envs
              name: Set environment variables
              run: |
                  prop() { grep -P "^\s*[^#]?${1}=.*$" './gradle.properties' | cut -d'=' -f2; }
                  echo "HARUHICORE_VERSION=`echo $(prop "haruhicore_version")`" >> $GITHUB_ENV
                  echo "MINECRAFT_VERSION=`echo $(prop "minecraft_version")`" >> $GITHUB_ENV
                  echo "CI_VERSION=`echo dev-rev.${GITHUB_SHA:0:7}-build.${{github.run_number}}`" >> $GITHUB_ENV

            - id: set_outputs
              name: Set outputs
              run: |
                  echo "::set-output name=ci_version::${{env.CI_VERSION}}"
                  echo "::set-output name=full_version::haruhicore-${{env.MINECRAFT_VERSION}}-${{env.HARUHICORE_VERSION}}-${{env.CI_VERSION}}"

    second:
        name: Build
        runs-on: ubuntu-latest
        needs: first
        env:
            CI_VERSION: ${{needs.first.outputs.ci_version}}
            FULL_VERSION: ${{needs.first.outputs.full_version}}

        steps:
            - uses: actions/checkout@v2

            - id: build_test
              run: echo "${{env.FULL_VERSION}}"
