# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: dev-build

on:
    push:
        branches:
            - 1.18-forge
        tags-ignore:
            - 'v*'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  architecture: x64

            - name: Set up Gradle
              run: |
                  chmod +x ./gradlew
                  rm -rf tmp
                  mkdir tmp

            - name: Build with Gradle
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              run: ./gradlew clean build outputProjectFullname

            - name: Read project full name
              run: echo "PROJECT_FULL_NAME=`cat ./tmp/fullname.txt`" >> $GITHUB_ENV

            - name: Upload build artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: ${{env.PROJECT_FULL_NAME}}
                  path: build/libs
